[package]
name = "golem-worker-bridge"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "Worker Bridge acts as a bridge between external API gateways and the worker's environment"

[lib]


[dependencies]
golem-common = { path = "../golem-common" }
