[package]
name = "golem-worker-bridge"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "Worker Bridge acts as a bridge between external API gateways and the worker's environment"

[lib]


[dependencies]
cloud-api-grpc = { path = "../golem-api-grpc" }
cloud-common = { path = "../golem-common" }

async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
figment = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http_02 = { package = "http", version = "0.2.11" }
hyper = { workspace = true }
nom = "7.1.3"
poem = { workspace = true, features = ["prometheus", "opentelemetry"] }
poem-openapi = { workspace = true }
prometheus = { workspace = true }
regex = "1.10.3"
rusoto_acm = "0.48.0"
rusoto_core = "0.48.0"
rusoto_credential = "0.48.0"
rusoto_elbv2 = "0.48.0"
rusoto_route53 = "0.48.0"
rusoto_sts = "0.48.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "std", "json"] }
url = { workspace = true }
uuid = { workspace = true }
warp = { workspace = true }
x509-certificate = "0.23.1"

[dev-dependencies]
reqwest = { workspace = true }