[package]
name = "wit-value"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
# crate-type = ["cdylib"]

[[bin]]
path = "src/main.rs"
name = "wit-value-test"

[dependencies]
wit-bindgen = { version = "0.17.0", default-features = false, features = ["realloc"] }

arbitrary = { version = "1.3.2", features = ["derive"], optional = true }
serde_json = { version = "1.0.113", optional = true }
prost = { version = "0.12.3", optional = true }
wasmtime = { version = "17.0.0", optional = true }

[dev-dependencies]
proptest = "1.4.0"
proptest-arbitrary-interop = "0.1.0"

[build-dependencies]
prost-build = "0.12.3"

[features]
default = ["arbitrary", "json", "protobuf", "wasmtime", "stub"]
arbitrary = ["dep:arbitrary"]
json = ["dep:serde_json"]
protobuf = ["dep:prost"]
stub = []


[package.metadata.component]
package = "golem:rpc"

[package.metadata.component.target]
path = "wit"
