[package]
name = "wasm-ast"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "WASM AST"

[dependencies]
mappable-rc = "0.1.1"
wasmparser = { version = "0.116.1", optional = true }
wasm-encoder = { version = "0.36.2", optional = true }
wasm-metadata = { version = "0.10.11", optional = true }
leb128 = {  version = "0.2.5", optional = true }

[dev-dependencies]
colored-diff = "0.2.3"
pretty_assertions = "1.4.0"
wasmprinter = "0.2.72"

[features]
default = ["parser", "writer", "component", "metadata", "analysis"]

# Support building up the WASM AST by parsing a binary WASM module or component using the wasmparser library
parser = ["dep:wasmparser", "dep:leb128"]

# Support writing out a binary WASM module or component using the wasm-encoder library
writer = ["dep:wasm-encoder"]

# Support for the WASM component model
component = []

# Support for extracting producer and other metadata from a binary WASM module or component using the wasm-metadata library
metadata = ["dep:wasm-metadata"]

# Enables some higher level analysis features built on top of the WASM AST
analysis = ["component"]

[lib]
path = "src/lib.rs"
