[workspace]
resolver = "2"

members = ["wasm-rpc", "wasm-rpc-stubgen", "wasm-rpc-stubgen/tests-integration"]

exclude = ["tmp"]

[profile.release]
debug = false
lto = true
opt-level = 's'

[workspace.dependencies]
assert2 = "0.3.15"
fs_extra = "1.3.0"
golem-wasm-ast = "1.1.0"
tempfile = "3.12.0"
test-r = { version = "1.1.0", default-features = false }
tokio = "1.38.0"
