version: '3'

x-ports:
  redis: &redis-port 6379
  postgres: &postgres-port 5432
  cloud_server_http: &cloud-server-http-port 9001
  cloud_server_grpc: &cloud-server-grpc-port 9090
  shard_manager_http: &shard-manager-http-port 8081
  shard_manager_grpc: &shard-manager-grpc-port 9002
  worker_executor_http: &worker-executor-http-port 8082
  worker_executor_grpc: &worker-executor-grpc-port 9000

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - *redis-port

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: golem_db
      POSTGRES_USER: golem_user
      POSTGRES_PASSWORD: golem_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - *postgres-port

  golem-shard-manager:
    build:
      context: .
      dockerfile: golem-shard-manager/docker/Dockerfile
    environment:
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=*redis-port
      - GOLEM__HTTP_PORT=*shard-manager-http-port
      - GOLEM_SHARD_MANAGER_PORT=*shard-manager-grpc-port
    depends_on:
      - redis

  golem-cloud-server-oss:
    build:
      context: .
      dockerfile: golem-cloud-server-oss/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - RUST_LOG="debug,h2=warn,hyper=warn,tower=warn"
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__TEMPLATES__STORE__TYPE="Local"
      - GOLEM__TEMPLATES__STORE__CONFIG__OBJECT_PREFIX=""
      - GOLEM__TEMPLATES__STORE__CONFIG__ROOT_PATH=/template_store
      - GOLEM__DB__TYPE=Postgres
      - GOLEM__DB__CONFIG__DATABASE=golem_db
      - GOLEM__DB__CONFIG__MAX_CONNECTIONS=10
      - GOLEM__DB__CONFIG__HOST=postgres
      - GOLEM__DB__CONFIG__USERNAME=golem_user
      - GOLEM__DB__CONFIG__PASSWORD=golem_password
      - GOLEM__ROUTING_TABLE__HOST=golem-shard-manager
      - GOLEM__ROUTING_TABLE__PORT=*shard-manager-grpc-port
      - GOLEM__GRPC_PORT=*cloud-server-grpc-port
      - GOLEM__HTTP_PORT=*cloud-server-http-port
    volumes:
      - template_store:/template_store
    ports:
      - *cloud-server-http-port
      - *cloud-server-grpc-port
    depends_on:
      - postgres

  golem-worker-executor-oss:
    build:
      context: .
      dockerfile: golem-worker-executor-oss/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - RUST_LOG=info
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__REDIS__PORT=6379
      - GOLEM__REDIS__HOST=redis
      - GOLEM__TEMPLATE_SERVICE__CONFIG__HOST=golem-cloud-server-oss
      - GOLEM__TEMPLATE_SERVICE__CONFIG__PORT=*cloud-server-grpc-port
      - GOLEM__TEMPLATE_SERVICE__CONFIG__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__PORT=*worker-executor-grpc-port
      - GOLEM__HTTP_PORT=*worker-executor-http-port
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__HOST=golem-shard-manager
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__PORT=*shard-manager-grpc-port
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_ATTEMPTS=5
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MIN_DELAY="100ms"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_DELAY="2s"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MULTIPLIER=2
      - GOLEM__BLOB_STORE_SERVICE__CONFIG__REGION=us-east-1
      - GOLEM__COMPILED_TEMPLATE_SERVICE__CONFIG__ROOT="data/templates"
      - GOLEM__COMPILED_TEMPLATE_SERVICE__TYPE="Local"
      - GOLEM__SHARD_MANAGER_SERVICE__TYPE="Grpc"
    ports:
      - *worker-executor-http-port

volumes:
  redis_data:
    driver: local
  template_store:
    driver: local
  postgres_data:
    driver: local