version: '3'

services:
  aws-local-s3:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  golem-shard-manager:
    build:
      context: .
      dockerfile: golem-shard-manager/docker/amd64/Dockerfile
      args:
        - REDIS_HOST=redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

  golem-cloud-server-oss:
    build:
      context: .
      dockerfile: golem-cloud-server-oss/docker/amd64/Dockerfile
      args:
        - SHARD_MANAGER_HOST=golem-shard-manager
        - SHARD_MANAGER_PORT=9001
        - TEMPLATES__STORE__ROOT_PATH=myfile
    ports:
      - "8080:8080"
      - "9090:9090"
      - "9001:9001"

  golem-worker-executor-oss:
    build:
      context: .
      dockerfile: golem-worker-executor-oss/docker/amd64/Dockerfile
      args:
        - ENVIRONMENT=local
        - CLOUD_SERVICE_HOST=golem-cloud-server-oss
        - SHARD_MANAGER_HOST=golem-shard-manager
        - SHARD_MANAGER_PORT=9001
        - REDIS_HOST=redis
        - AWS_ACCESS_KEY_ID=root
        - AWS_SECRET_ACCESS_KEY=root
        - AWS_DEFAULT_REGION=us-east-1
        - S3_ENDPOINT=http://aws-s3:4566
    ports:
      - "9000:9000"