version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  golem-shard-manager:
    build:
      context: .
      dockerfile: golem-shard-manager/docker/amd64/Dockerfile
      args:
        - REDIS_HOST=redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

  golem-cloud-server-oss:
    build:
      context: .
      dockerfile: golem-cloud-server-oss/docker/amd64/Dockerfile
      args:
        - SHARD_MANAGER_HOST=golem-shard-manager
        - SHARD_MANAGER_PORT=8081
        - TEMPLATES__STORE__ROOT_PATH=myfile
    ports:
      - "8080:8080"
      - "9090:9090"
      - "9001:9001"

  golem-worker-executor-oss:
    build:
      context: .
      dockerfile: golem-worker-executor-oss/docker/amd64/Dockerfile
      args:
        - ENVIRONMENT=local
        - CLOUD_SERVICE_HOST=golem-cloud-server-oss
        - SHARD_MANAGER_HOST=golem-shard-manager
        - SHARD_MANAGER_PORT=9001
    ports:
      - "9000:9000"