[package]
name = "golem-wasm-rpc"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/wasm-rpc"
description = "Golem WASM RPC support library"

include = []

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen-rt = { version = "0.26.0", features = ["bitflags"] }

arbitrary = { version = "1.3.2", features = ["derive"], optional = true }
bigdecimal = { version = "0.4.5", optional = true }
bincode = { version = "2.0.0-rc.3", optional = true }
golem-wasm-ast = { version = "0.2.2", features = ["analysis", "wave"], optional = true }
serde = { version = "1.0.203", optional = true }
serde_json = { version = "1.0.117", optional = true }
prost = { version = "0.12.6", optional = true }
wasmtime = { version = "=21.0.1", features = ["component-model"], optional = true }
wasm-wave = { version = "=0.6.0", optional = true }

[dev-dependencies]
proptest = "1.4.0"
proptest-arbitrary-interop = "0.1.0"

[build-dependencies]
prost-build = "0.12.6"

[features]
default = ["host"]
host = ["arbitrary", "bincode", "json", "protobuf", "serde", "text", "typeinfo", "wasmtime"]
arbitrary = ["dep:arbitrary"]
bincode = ["dep:bincode"]
json = ["dep:serde", "dep:serde_json", "dep:bigdecimal", "typeinfo"]
protobuf = ["dep:bincode", "dep:serde", "dep:prost"]
serde = ["dep:serde"]
stub = []
text = ["wasmtime", "dep:wasm-wave"]
typeinfo = ["dep:golem-wasm-ast"]
wasmtime = ["dep:wasmtime", "typeinfo"]


[package.metadata.component]
package = "golem:rpc"

[package.metadata.component.target]
path = "wit"
