port = 9000
http_port = 9100

enable_tracing_console = false
enable_json_log = false

promise_poll_interval = "1s"

[limits]
max_active_instances = 1024
concurrency_limit_per_connection = 1024
max_concurrent_streams = 1024
event_broadcast_capacity = 16
event_history_size = 128
fuel_to_borrow = 10000

[retry]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[template_cache]
max_capacity = 32
time_to_idle = "12h"

[template_service]
type = "Local"

[template_service.config]
root = "data/templates"

[compiled_template_service]
type = "Local"

[compiled_template_service.config]
root = "data/compiled_templates"

[blob_store_service]
type = "InMemory"

[blob_store_service.config]

[key_value_service]
type = "InMemory"

[redis]
host = "unused"
port = 0
database = 0
tracing = false
pool_size = 8
key_prefix = ""

[redis.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[shard_manager_service]
type = "Grpc"

[shard_manager_service.config]
host = "localhost"
port = "9001"

[shard_manager_service.config.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[promises]
type = "InMemory"

[workers]
type = "InMemory"