openapi: 3.0.0
x-API-Definition-Id : "my-api"
info:
  title: Sample API
  version: 1.0.0
paths:
  /users/{id}:
    x-worker-bridge:
      worker-id: "myworker"
      function-name: "golem:it/api/get-cart-contents"
      function-params: []
      template-id: "4d1b159d-51d3-4440-aa29-8edb235f62a3"
    get:
      summary: Get user by ID
      description: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '404':
          description: User not found