[package]
name = "golem-it-http-client"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
reqwest = { git = "https://github.com/zivergetech/reqwest", branch = "update-jan-2024", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cargo-component-bindings = { version = "0.5.0" }

[package.metadata.component]
package = "golem:it"

[package.metadata.component.target]
path = "wit"
