enable_tracing_console = false
enable_json_log = false
# workspace
# environment
port = 9000
custom_request_port = 9001
worker_grpc_port = 9091

[db]
type = "Postgres" # Postgres, Sqlite

[db.config]
max_connections = 10
host = "localhost"
port = 5432
database = "golem_worker"
#username
#password
#schema

[cloud_service]
# host
# port
# access_token

[cloud_service.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[component_service]
# host
# port
# access_token

[component_service.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[domain_records]
subdomain_black_list = ["api-gateway", "release", "grafana"]
domain_allow_list = []
register_domain_black_list = ["api.golem.cloud", "dev-api.golem.cloud"]

[routing_table]
# host
# port

[worker_executor_client_cache]
max_capacity = 1000
time_to_idle = "4h"