[package]
name = "golem-rib"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Parser for Golem's Rib language"

[dependencies]
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }
golem-wasm-ast = { path = "../wasm-ast", version = "0.0.0" }
golem-wasm-rpc = { path = "../wasm-rpc", version = "0.0.0", default-features = false, features = ["host"] }

async-trait = { workspace = true }
bigdecimal = {workspace = true }
bincode = { workspace = true }
combine = { workspace = true }
poem-openapi = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = {workspace = true}
wasm-wave = { workspace = true }

[dev-dependencies]
test-r = { workspace = true }

[lib]
name = "rib"
path = "src/lib.rs"
harness = false